name: Deploy to Firebase Hosting
'on':
  push:
    branches: [main, stage]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci 
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PAW_ADOPT_44AE0 }}'
          channelId: live
          projectId: paw-adopt-44ae0
        env:
            FIREBASE_CLI_EXPERIMENTS: webframeworks
