name: Auto PR reviewer

on:  
  pull_request:
    types: [opened, reopened, labeled, edited]

  pull_request_review:
      types: [dismissed]

permissions: 
  pull-requests: write
  contents: read



jobs:
  autoapproval:
    runs-on: ubuntu-latest
    name: Autoapproval

    steps:
    - name: Run tests
      run: | 
        npm install
        npm test

    - name: Approve pull request
      uses: dkhmelenko/autoapproval@v1.0

      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
    
        
      
