name: Auto PR reviewer

on:  
  pull_request:
    types: [opened, reopened, labeled, edited]

permissions: 
  pull-requests: write
  contents: read

jobs:
  autoapproval:
    runs-on: ubuntu-latest
    name: Autoapproval

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: | 
        npm install
        npm test

    - name: Approve pull request
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"