name: PR reviewer

on:
  push:
    branches: [main, stage, development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Run tests
      run: npm test

    - name: Approve and merge pull request
      if: success()
      run: |
        gh pr review ${{ github.event.pull_request.number }} --approve
        gh pr merge ${{ github.event.pull_request.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
